import type { DummyRuleMap } from "vite-plus/lint"

export const style: DummyRuleMap = {
  // error
  "eslint/init-declarations": "error",
  "eslint/max-params": ["error", { max: 4 }],
  "eslint/max-statements": ["error", { max: 20 }],
  "eslint/no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
  "eslint/prefer-destructuring": "error",
  "eslint/prefer-template": "error",
  "eslint/sort-imports": ["error", { ignoreDeclarationSort: true }],
  "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
  "import/no-mutable-exports": "error",
  "import/no-namespace": ["error", { ignore: [] }],
  "import/no-nodejs-modules": "error",
  "promise/prefer-await-to-then": ["error", { strict: true }],
  "react/jsx-max-depth": ["error", { max: 5 }],
  "typescript/array-type": "error",
  "typescript/consistent-type-definitions": "error",
  "unicorn/catch-error-name": "error",
  "unicorn/consistent-existence-index-check": "error",
  "unicorn/no-useless-collection-argument": "error",
  "unicorn/relative-url-style": "error",
  "unicorn/text-encoding-identifier-case": "error",
  "vitest/prefer-strict-boolean-matchers": "error",

  // off
  "eslint/arrow-body-style": "off",
  "eslint/capitalized-comments": "off",
  "eslint/curly": "off",
  "eslint/func-style": "off",
  "eslint/id-length": "off",
  "eslint/no-continue": "off",
  "eslint/no-implicit-coercion": "off",
  "eslint/no-magic-numbers": "off",
  "eslint/no-nested-ternary": "off",
  "eslint/no-ternary": "off",
  "eslint/sort-keys": "off",
  "import/exports-last": "off",
  "import/group-exports": "off",
  "import/no-named-export": "off",
  "import/prefer-default-export": "off",
  "promise/prefer-await-to-callbacks": "off",
  "react/jsx-handler-names": "off",
  "react/jsx-props-no-spreading": "off",
  "typescript/consistent-indexed-object-style": "off",
  "unicorn/filename-case": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-null": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-global-this": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/switch-case-braces": "off",
  "vitest/prefer-describe-function-title": "off",
  "vitest/prefer-importing-vitest-globals": "off",
  "vitest/prefer-lowercase-title": "off",
  "vitest/prefer-to-be-falsy": "off",
  "vitest/prefer-to-be-truthy": "off",
  "vitest/require-hook": "off",
}
